#ifndef __sosapp__
#define __sosapp__

enum {
	SOSROUTING_STATUS_INIT,
	SOSROUTING_STATUS_START,
	SOSROUTING_STATUS_SENDSMS1,
	SOSROUTING_STATUS_SENDSMSDELAY1,
	SOSROUTING_STATUS_SENDSMSDELAY2,
	SOSROUTING_STATUS_SENDSMSDELAY3,
	SOSROUTING_STATUS_SENDSMSDELAY4,
	SOSROUTING_STATUS_CALL,
	SOSROUTING_STATUS_FINISH,
};
extern unsigned char sosrouting_status;
void sos_routing(void);

#endif
